# Jupyter-NotebookでのRの利用方法
動作確認をします

In [1]:
data <- c(0.7,-1.6,-0.2,-1.2,-0.1,3.4,3.7,0.8,0.0,2.0) 
summary(data)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -1.600  -0.175   0.350   0.750   1.700   3.700 

### 簡単なベクトル計算
j:k は、要素 [j,j+1,j+2,...,j+m] をもつ、間隔が 1 のベクトル を作成単純に [j,j+1,...,k] になります。

In [2]:
x <- 1:10
x #表示

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
x + 1 #ベクトルに1を足して表示

[1]  2  3  4  5  6  7  8  9 10 11

In [4]:
x <- x + 1　#ベクトル自体に1を加算
x #表示

[1]  2  3  4  5  6  7  8  9 10 11

#### 内積
内積は`%*%`を利用  
`*`の場合は成分同士の積

In [5]:
#内積
x1 <- c(1,2)
x2 <- c(3,4)
x3 <- x1 %*% x2
x3

[,1]
[1,] 11

In [6]:
#成分同士の積
x3 <- x1 * x2
x3

[1] 3 8

#### 行列
行列はベクトルを並べたもの  
行列を作成：matrix() を利用  
nrow : 行数を指定、または　ncol : 列数を指定  
byrow : TRUEの時、横方向に成分が生成される

In [7]:
mtx <- matrix(1:9, nrow = 3) #1~9までの数値の行数3の行列を作成
#デフォルトでは縦方向に成分が埋められる
mtx

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
mtx <- matrix(1:15, nrow = 3) #1~15までの数値の行数3の行列を作成
mtx

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [9]:
mtx <- matrix(1:9, nrow = 3, byrow =TRUE)
#1~9までの数値を行数3,横方向に成分を埋めるように指定
mtx

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [10]:
mtx <- matrix(1:15, nrow = 5, byrow =TRUE)
#1~15までの数値の行数5,横方向に成分を埋めるように指定
mtx

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12  
[5,] 13   14   15

#### 行列計算
行列の積は内積同様`%*%`を利用

In [11]:
mtx1 <- matrix(c(1,2,3,4), nrow = 2, byrow =TRUE) 
mtx1

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [12]:
mtx2 <- matrix(c(1,2,3,4), nrow = 2) 
mtx2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [13]:
mtx3 <- mtx1 %*% mtx2
mtx3

[,1] [,2]
[1,]  5   11  
[2,] 11   25

#### データフレーム
データフレームは、データ型を混在させることができる  
データ解析では最も利用されるデータ構造  
データフレームを作成：data.frame()を利用

In [14]:
# データフレームの作成
df <- data.frame(
    lang = c(70, 76, 49, 86, 95), #numeric
    math = c(87, 64, 40, 59, 97), #numeric
    rank = c("B", "C", "D", "B","A") #character
)
df

lang math rank
1 70   87   B   
2 76   64   C   
3 49   40   D   
4 86   59   B   
5 95   97   A

#### データフレームの操作

In [15]:
# 1行目の列を全て抽出
df[1,] 

lang math rank
1 70   87   B

In [16]:
#1列目の行を全て抽出
df[,1]

[1] 70 76 49 86 95

In [17]:
# 複数の行を抽出
df[1:3,1] #1~3行を抽出

[1] 70 76 49

In [18]:
# 複数の行を抽出
df[c(1,3),] #1と3行を抽出

lang math rank
1 70   87   B   
3 49   40   D

## Markdownの基本
### ◻︎スタイル
**太字** `**太字**`  
_斜体_　 `_斜体_`　　　  
> ブロック引用　 `> ブロック引用　`　

### ◻︎見出し
# 見出し 1 `# 見出し 1`
## 見出し 2 `## 見出し 2`
### 見出し 3  `### 見出し 3`
#### 見出し 4  `#### 見出し 4`

### ◻︎水平線
`- - - `
- - - 

### ◻︎改行
文章の最後に、半角スペース2つ  

### ◻︎リンク
[Fukuoka IST](http://www.ist.or.jp/)
`[Fukuoka IST](http://www.ist.or.jp/)`

### ◻︎コード
マークダウン中に実行されたくないコードを書きたい場合は、 `でコードを囲む